#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 14 14:01:31 2018

@author: ssrinivasan.19
"""

import numpy as np 
import matplotlib.pyplot as plt
from matplotlib import style
style.use("ggplot")
from sklearn import svm

X = np.array([[1,2],
             [5,8],
             [1.5,1.8],
             [8,8],
             [1,0.6],
             [9,11]])

print X
y = [0,1,0,1,0,1]

plt.scatter(x,y)
plt.show()

clf = svm.SVC(kernel = 'linear', C = 1.0)

clf.fit(X,y)



print(clf.predict([[1.2,0.45]]))



